# Generated by Django 5.0.3 on 2024-03-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='da_bubble_user',
            old_name='avatarname',
            new_name='avatar',
        ),
    ]
