# Generated by Django 5.0.3 on 2024-03-16 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 16, 54, 38, 961247)),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 16, 54, 38, 961459)),
        ),
    ]
